DROP TABLE CONTATTO;
DROP TABLE UtenteRegistrato;
DROP TABLE MailingList;
DROP TABLE FOTOGRAFIA;
DROP TABLE Annuncio;
DROP TABLE INSERZIONISTA;

DROP SEQUENCE SEQUENZA_ANNUNCIO;
DROP SEQUENCE SEQUENZA_CONTATTO;
DROP SEQUENCE SEQUENZA_FOTOGRAFIA;
DROP SEQUENCE SEQUENZA_INSERZIONISTA;
DROP SEQUENCE SEQUENZA_UTENTEREGISTRATO;
